#############################################################################
# Makefile for building: qtgr
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Jul 29 20:28:56 2013
# Project:  qtgr.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile qtgr.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = edit.cpp \
		file.cpp \
		graphwidget.cpp \
		main.cpp \
		mainwindow.cpp \
		tools.cpp \
		view.cpp \
		view/ticks.cpp \
		view/symbols.cpp \
		view/world.cpp \
		base/alerts.c \
		base/checkon.c \
		base/chersh.c \
		base/defaults.c \
		base/draw.c \
		base/drawticks.c \
		base/events.c \
		base/files.c \
		base/fit.c \
		base/graphutils.c \
		base/objutils.c \
		base/pars.c \
		base/plotone.c \
		base/qtlib.c \
		base/utils.c \
		base/setutils.c \
		base/getparms.c \
		base/setprops.c \
		base/compute.c \
		base/computils.c \
		base/fourier.c \
		base/lmdif1.c \
		base/params.c \
		base/regionutils.c \
		view/graphtype.cpp \
		view/legends.cpp \
		transform.cpp \
		transform/integration.cpp \
		dialog.cpp \
		view/viewport.cpp \
		transform/differentiation.cpp \
		transform/evaluate.cpp \
		view/title.cpp \
		setcombobox.cpp \
		prop.cpp \
		overlay.cpp moc_edit.cpp \
		moc_file.cpp \
		moc_graphwidget.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp \
		moc_ticks.cpp \
		moc_symbols.cpp \
		moc_world.cpp \
		moc_tools.cpp \
		moc_graphtype.cpp \
		moc_legends.cpp \
		moc_transform.cpp \
		moc_integration.cpp \
		moc_dialog.cpp \
		moc_viewport.cpp \
		moc_differentiation.cpp \
		moc_evaluate.cpp \
		moc_title.cpp \
		moc_setcombobox.cpp \
		moc_prop.cpp \
		moc_overlay.cpp \
		qrc_qtgr.cpp
OBJECTS       = edit.o \
		file.o \
		graphwidget.o \
		main.o \
		mainwindow.o \
		tools.o \
		view.o \
		ticks.o \
		symbols.o \
		world.o \
		alerts.o \
		checkon.o \
		chersh.o \
		defaults.o \
		draw.o \
		drawticks.o \
		events.o \
		files.o \
		fit.o \
		graphutils.o \
		objutils.o \
		pars.o \
		plotone.o \
		qtlib.o \
		utils.o \
		setutils.o \
		getparms.o \
		setprops.o \
		compute.o \
		computils.o \
		fourier.o \
		lmdif1.o \
		params.o \
		regionutils.o \
		graphtype.o \
		legends.o \
		transform.o \
		integration.o \
		dialog.o \
		viewport.o \
		differentiation.o \
		evaluate.o \
		title.o \
		setcombobox.o \
		prop.o \
		overlay.o \
		moc_edit.o \
		moc_file.o \
		moc_graphwidget.o \
		moc_mainwindow.o \
		moc_view.o \
		moc_ticks.o \
		moc_symbols.o \
		moc_world.o \
		moc_tools.o \
		moc_graphtype.o \
		moc_legends.o \
		moc_transform.o \
		moc_integration.o \
		moc_dialog.o \
		moc_viewport.o \
		moc_differentiation.o \
		moc_evaluate.o \
		moc_title.o \
		moc_setcombobox.o \
		moc_prop.o \
		moc_overlay.o \
		qrc_qtgr.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtgr.pro
QMAKE_TARGET  = qtgr
DESTDIR       = 
TARGET        = qtgr

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtgr.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile qtgr.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile qtgr.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtgr1.0.0 || $(MKDIR) .tmp/qtgr1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents edit.h file.h graphwidget.h base/globals.h base/defines.h base/pars.h base/externs.h base/hersh.h base/patterns.h base/special.h base/symdefs.h base/f2c.h mainwindow.h mousecall.h view.h view/ticks.h view/symbols.h view/world.h tools.h view/graphtype.h view/legends.h transform.h transform/integration.h dialog.h view/viewport.h transform/differentiation.h transform/evaluate.h view/title.h setcombobox.h prop.h overlay.h .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents qtgr.qrc .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents edit.cpp file.cpp graphwidget.cpp main.cpp mainwindow.cpp tools.cpp view.cpp view/ticks.cpp view/symbols.cpp view/world.cpp base/alerts.c base/checkon.c base/chersh.c base/defaults.c base/draw.c base/drawticks.c base/events.c base/files.c base/fit.c base/graphutils.c base/objutils.c base/pars.c base/plotone.c base/qtlib.c base/utils.c base/setutils.c base/getparms.c base/setprops.c base/compute.c base/computils.c base/fourier.c base/lmdif1.c base/params.c base/regionutils.c view/graphtype.cpp view/legends.cpp transform.cpp transform/integration.cpp dialog.cpp view/viewport.cpp transform/differentiation.cpp transform/evaluate.cpp view/title.cpp setcombobox.cpp prop.cpp overlay.cpp .tmp/qtgr1.0.0/ && (cd `dirname .tmp/qtgr1.0.0` && $(TAR) qtgr1.0.0.tar qtgr1.0.0 && $(COMPRESS) qtgr1.0.0.tar) && $(MOVE) `dirname .tmp/qtgr1.0.0`/qtgr1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtgr1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_edit.cpp moc_file.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_view.cpp moc_ticks.cpp moc_symbols.cpp moc_world.cpp moc_tools.cpp moc_graphtype.cpp moc_legends.cpp moc_transform.cpp moc_integration.cpp moc_dialog.cpp moc_viewport.cpp moc_differentiation.cpp moc_evaluate.cpp moc_title.cpp moc_setcombobox.cpp moc_prop.cpp moc_overlay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_edit.cpp moc_file.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_view.cpp moc_ticks.cpp moc_symbols.cpp moc_world.cpp moc_tools.cpp moc_graphtype.cpp moc_legends.cpp moc_transform.cpp moc_integration.cpp moc_dialog.cpp moc_viewport.cpp moc_differentiation.cpp moc_evaluate.cpp moc_title.cpp moc_setcombobox.cpp moc_prop.cpp moc_overlay.cpp
moc_edit.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		edit.h
	/usr/bin/moc $(DEFINES) $(INCPATH) edit.h -o moc_edit.cpp

moc_file.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		file.h
	/usr/bin/moc $(DEFINES) $(INCPATH) file.h -o moc_file.cpp

moc_graphwidget.cpp: mousecall.h \
		overlay.h \
		graphwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) graphwidget.h -o moc_graphwidget.cpp

moc_mainwindow.cpp: graphwidget.h \
		mousecall.h \
		overlay.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view/viewport.h \
		view/title.h \
		view.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view.h -o moc_view.cpp

moc_ticks.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view/ticks.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/ticks.h -o moc_ticks.cpp

moc_symbols.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view/symbols.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/symbols.h -o moc_symbols.cpp

moc_world.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		dialog.h \
		view/world.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/world.h -o moc_world.cpp

moc_tools.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		tools.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tools.h -o moc_tools.cpp

moc_graphtype.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view/graphtype.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/graphtype.h -o moc_graphtype.cpp

moc_legends.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view/legends.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/legends.h -o moc_legends.cpp

moc_transform.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		dialog.h \
		transform.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform.h -o moc_transform.cpp

moc_integration.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		transform/integration.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform/integration.h -o moc_integration.cpp

moc_dialog.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_viewport.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		dialog.h \
		view/viewport.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/viewport.h -o moc_viewport.cpp

moc_differentiation.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		transform/differentiation.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform/differentiation.h -o moc_differentiation.cpp

moc_evaluate.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		transform/evaluate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform/evaluate.h -o moc_evaluate.cpp

moc_title.cpp: dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view/title.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/title.h -o moc_title.cpp

moc_setcombobox.cpp: setcombobox.h
	/usr/bin/moc $(DEFINES) $(INCPATH) setcombobox.h -o moc_setcombobox.cpp

moc_prop.cpp: prop.h
	/usr/bin/moc $(DEFINES) $(INCPATH) prop.h -o moc_prop.cpp

moc_overlay.cpp: overlay.h
	/usr/bin/moc $(DEFINES) $(INCPATH) overlay.h -o moc_overlay.cpp

compiler_rcc_make_all: qrc_qtgr.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qtgr.cpp
qrc_qtgr.cpp: qtgr.qrc \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/usr/bin/rcc -name qtgr qtgr.qrc -o qrc_qtgr.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

edit.o: edit.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		edit.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		transform.h \
		dialog.h \
		prop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edit.o edit.cpp

file.o: file.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		file.h \
		base/globals.h \
		base/defines.h \
		base/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

graphwidget.o: graphwidget.cpp graphwidget.h \
		mousecall.h \
		overlay.h \
		mainwindow.h \
		base/globals.h \
		base/defines.h \
		base/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o graphwidget.cpp

main.o: main.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		file.h \
		edit.h \
		view.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view/viewport.h \
		view/title.h \
		tools.h \
		prop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tools.o: tools.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		tools.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		prop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o tools.cpp

view.o: view.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view/viewport.h \
		view/title.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o view.cpp

ticks.o: view/ticks.cpp view.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view/viewport.h \
		view/title.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ticks.o view/ticks.cpp

symbols.o: view/symbols.cpp view/symbols.h \
		dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view/viewport.h \
		view/title.h \
		setcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbols.o view/symbols.cpp

world.o: view/world.cpp view.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view/viewport.h \
		view/title.h \
		prop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o world.o view/world.cpp

alerts.o: base/alerts.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o alerts.o base/alerts.c

checkon.o: base/checkon.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o checkon.o base/checkon.c

chersh.o: base/chersh.c base/hersh.h \
		base/special.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o chersh.o base/chersh.c

defaults.o: base/defaults.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o defaults.o base/defaults.c

draw.o: base/draw.c base/symdefs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o draw.o base/draw.c

drawticks.o: base/drawticks.c base/globals.h \
		base/defines.h \
		base/pars.h \
		base/externs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o drawticks.o base/drawticks.c

events.o: base/events.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o events.o base/events.c

files.o: base/files.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o files.o base/files.c

fit.o: base/fit.c base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fit.o base/fit.c

graphutils.o: base/graphutils.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o graphutils.o base/graphutils.c

objutils.o: base/objutils.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objutils.o base/objutils.c

pars.o: base/pars.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pars.o base/pars.c

plotone.o: base/plotone.c base/globals.h \
		base/defines.h \
		base/pars.h \
		base/symdefs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o plotone.o base/plotone.c

qtlib.o: base/qtlib.c base/externs.h \
		base/patterns.h \
		graphwidget.h \
		mousecall.h \
		overlay.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o qtlib.o base/qtlib.c

utils.o: base/utils.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o utils.o base/utils.c

setutils.o: base/setutils.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setutils.o base/setutils.c

getparms.o: base/getparms.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o getparms.o base/getparms.c

setprops.o: base/setprops.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setprops.o base/setprops.c

compute.o: base/compute.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o compute.o base/compute.c

computils.o: base/computils.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o computils.o base/computils.c

fourier.o: base/fourier.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o fourier.o base/fourier.c

lmdif1.o: base/lmdif1.c base/f2c.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o lmdif1.o base/lmdif1.c

params.o: base/params.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o params.o base/params.c

regionutils.o: base/regionutils.c base/globals.h \
		base/defines.h \
		base/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o regionutils.o base/regionutils.c

graphtype.o: view/graphtype.cpp view/graphtype.h \
		dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		view.h \
		view/symbols.h \
		view/ticks.h \
		view/world.h \
		view/legends.h \
		view/viewport.h \
		view/title.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphtype.o view/graphtype.cpp

legends.o: view/legends.cpp view/legends.h \
		dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		setcombobox.h \
		view.h \
		view/symbols.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/viewport.h \
		view/title.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o legends.o view/legends.cpp

transform.o: transform.cpp transform.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		dialog.h \
		transform/integration.h \
		transform/differentiation.h \
		transform/evaluate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transform.o transform.cpp

integration.o: transform/integration.cpp transform/integration.h \
		dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		setcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integration.o transform/integration.cpp

dialog.o: dialog.cpp dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

viewport.o: view/viewport.cpp view/viewport.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		dialog.h \
		base/globals.h \
		base/defines.h \
		base/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewport.o view/viewport.cpp

differentiation.o: transform/differentiation.cpp transform/differentiation.h \
		dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		setcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o differentiation.o transform/differentiation.cpp

evaluate.o: transform/evaluate.cpp transform/evaluate.h \
		dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h \
		setcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o evaluate.o transform/evaluate.cpp

title.o: view/title.cpp view/title.h \
		dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		overlay.h \
		base/globals.h \
		base/defines.h \
		base/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o title.o view/title.cpp

setcombobox.o: setcombobox.cpp setcombobox.h \
		base/globals.h \
		base/defines.h \
		base/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setcombobox.o setcombobox.cpp

prop.o: prop.cpp prop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prop.o prop.cpp

overlay.o: overlay.cpp overlay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o overlay.o overlay.cpp

moc_edit.o: moc_edit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edit.o moc_edit.cpp

moc_file.o: moc_file.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_file.o moc_file.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_ticks.o: moc_ticks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ticks.o moc_ticks.cpp

moc_symbols.o: moc_symbols.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_symbols.o moc_symbols.cpp

moc_world.o: moc_world.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_world.o moc_world.cpp

moc_tools.o: moc_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tools.o moc_tools.cpp

moc_graphtype.o: moc_graphtype.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphtype.o moc_graphtype.cpp

moc_legends.o: moc_legends.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_legends.o moc_legends.cpp

moc_transform.o: moc_transform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transform.o moc_transform.cpp

moc_integration.o: moc_integration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_integration.o moc_integration.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_viewport.o: moc_viewport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewport.o moc_viewport.cpp

moc_differentiation.o: moc_differentiation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_differentiation.o moc_differentiation.cpp

moc_evaluate.o: moc_evaluate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_evaluate.o moc_evaluate.cpp

moc_title.o: moc_title.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_title.o moc_title.cpp

moc_setcombobox.o: moc_setcombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setcombobox.o moc_setcombobox.cpp

moc_prop.o: moc_prop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prop.o moc_prop.cpp

moc_overlay.o: moc_overlay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_overlay.o moc_overlay.cpp

qrc_qtgr.o: qrc_qtgr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtgr.o qrc_qtgr.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/edit.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/file.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/graphwidget.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/main.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mainwindow.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/tools.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/ticks.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/symbols.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/world.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/alerts.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/checkon.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/chersh.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/defaults.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/draw.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/drawticks.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/events.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/files.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/fit.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/graphutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/objutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/pars.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/plotone.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/qtlib.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/utils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/setutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/getparms.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/setprops.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/compute.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/computils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/fourier.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/lmdif1.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/params.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/regionutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/graphtype.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/legends.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/integration.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/dialog.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/viewport.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/differentiation.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/evaluate.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/title.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/setcombobox.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/prop.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/overlay.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/edit.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/file.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/graphwidget.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/globals.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/defines.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/pars.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/externs.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/hersh.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/patterns.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/special.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/symdefs.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/base/f2c.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mainwindow.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mousecall.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/ticks.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/symbols.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/world.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/tools.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/graphtype.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/legends.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/integration.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/dialog.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/viewport.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/differentiation.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/evaluate.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/title.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/setcombobox.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/prop.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/overlay.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/qtgr.qrc $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/qtgr.pro $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_DIR) /home/msto/code/pappus/qtgr/images $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/edit.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/file.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphwidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mainwindow.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/tools.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ticks.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/symbols.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/world.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/alerts.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/checkon.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/chersh.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/defaults.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/draw.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/drawticks.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/events.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/files.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/fit.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/objutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/pars.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/plotone.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtlib.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/utils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/getparms.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setprops.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/compute.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/computils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/fourier.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/lmdif1.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/params.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/regionutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphtype.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/legends.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/transform.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/integration.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/dialog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/viewport.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/differentiation.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/evaluate.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/title.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setcombobox.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/prop.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/overlay.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/edit.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/file.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/globals.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/defines.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/pars.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/externs.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/hersh.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/patterns.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/special.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/symdefs.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/f2c.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mainwindow.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mousecall.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ticks.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/symbols.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/world.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/tools.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphtype.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/legends.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/transform.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/integration.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/dialog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/viewport.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/differentiation.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/evaluate.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/title.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setcombobox.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/prop.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/overlay.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtgr.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtgr.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/images
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

