#############################################################################
# Makefile for building: qtgr
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sat Jul 27 20:25:43 2013
# Project:  qtgr.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qtgr.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = edit.cpp \
		file.cpp \
		graphwidget.cpp \
		main.cpp \
		mainwindow.cpp \
		tools.cpp \
		view.cpp \
		view/ticks.cpp \
		view/symbols.cpp \
		view/world.cpp \
		core/alerts.c \
		core/checkon.c \
		core/chersh.c \
		core/defaults.c \
		core/draw.c \
		core/drawticks.c \
		core/events.c \
		core/files.c \
		core/fit.c \
		core/graphutils.c \
		core/objutils.c \
		core/pars.c \
		core/plotone.c \
		core/qtlib.c \
		core/utils.c \
		core/setutils.c \
		core/getparms.c \
		core/setprops.c \
		view/graphtype.cpp \
		view/legends.cpp \
		transform.cpp \
		transform/integration.cpp \
		dialog.cpp \
		view/viewport.cpp moc_edit.cpp \
		moc_file.cpp \
		moc_graphwidget.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp \
		moc_ticks.cpp \
		moc_symbols.cpp \
		moc_world.cpp \
		moc_tools.cpp \
		moc_graphtype.cpp \
		moc_legends.cpp \
		moc_transform.cpp \
		moc_integration.cpp \
		moc_dialog.cpp \
		moc_viewport.cpp \
		qrc_qtgr.cpp
OBJECTS       = edit.o \
		file.o \
		graphwidget.o \
		main.o \
		mainwindow.o \
		tools.o \
		view.o \
		ticks.o \
		symbols.o \
		world.o \
		alerts.o \
		checkon.o \
		chersh.o \
		defaults.o \
		draw.o \
		drawticks.o \
		events.o \
		files.o \
		fit.o \
		graphutils.o \
		objutils.o \
		pars.o \
		plotone.o \
		qtlib.o \
		utils.o \
		setutils.o \
		getparms.o \
		setprops.o \
		graphtype.o \
		legends.o \
		transform.o \
		integration.o \
		dialog.o \
		viewport.o \
		moc_edit.o \
		moc_file.o \
		moc_graphwidget.o \
		moc_mainwindow.o \
		moc_view.o \
		moc_ticks.o \
		moc_symbols.o \
		moc_world.o \
		moc_tools.o \
		moc_graphtype.o \
		moc_legends.o \
		moc_transform.o \
		moc_integration.o \
		moc_dialog.o \
		moc_viewport.o \
		qrc_qtgr.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtgr.pro
QMAKE_TARGET  = qtgr
DESTDIR       = 
TARGET        = qtgr

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtgr.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile qtgr.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtgr.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtgr1.0.0 || $(MKDIR) .tmp/qtgr1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents edit.h file.h graphwidget.h core/globals.h core/defines.h core/pars.h core/externs.h core/hersh.h core/patterns.h core/special.h core/symdefs.h mainwindow.h mousecall.h view.h view/ticks.h view/symbols.h view/world.h tools.h view/graphtype.h view/legends.h transform.h transform/integration.h dialog.h view/viewport.h .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents qtgr.qrc .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents edit.cpp file.cpp graphwidget.cpp main.cpp mainwindow.cpp tools.cpp view.cpp view/ticks.cpp view/symbols.cpp view/world.cpp core/alerts.c core/checkon.c core/chersh.c core/defaults.c core/draw.c core/drawticks.c core/events.c core/files.c core/fit.c core/graphutils.c core/objutils.c core/pars.c core/plotone.c core/qtlib.c core/utils.c core/setutils.c core/getparms.c core/setprops.c view/graphtype.cpp view/legends.cpp transform.cpp transform/integration.cpp dialog.cpp view/viewport.cpp .tmp/qtgr1.0.0/ && (cd `dirname .tmp/qtgr1.0.0` && $(TAR) qtgr1.0.0.tar qtgr1.0.0 && $(COMPRESS) qtgr1.0.0.tar) && $(MOVE) `dirname .tmp/qtgr1.0.0`/qtgr1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtgr1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_edit.cpp moc_file.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_view.cpp moc_ticks.cpp moc_symbols.cpp moc_world.cpp moc_tools.cpp moc_graphtype.cpp moc_legends.cpp moc_transform.cpp moc_integration.cpp moc_dialog.cpp moc_viewport.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_edit.cpp moc_file.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_view.cpp moc_ticks.cpp moc_symbols.cpp moc_world.cpp moc_tools.cpp moc_graphtype.cpp moc_legends.cpp moc_transform.cpp moc_integration.cpp moc_dialog.cpp moc_viewport.cpp
moc_edit.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		edit.h
	/usr/bin/moc $(DEFINES) $(INCPATH) edit.h -o moc_edit.cpp

moc_file.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		file.h
	/usr/bin/moc $(DEFINES) $(INCPATH) file.h -o moc_file.cpp

moc_graphwidget.cpp: mousecall.h \
		graphwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) graphwidget.h -o moc_graphwidget.cpp

moc_mainwindow.cpp: graphwidget.h \
		mousecall.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		view/viewport.h \
		view.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view.h -o moc_view.cpp

moc_ticks.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		view/ticks.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/ticks.h -o moc_ticks.cpp

moc_symbols.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		view/symbols.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/symbols.h -o moc_symbols.cpp

moc_world.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		view/world.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/world.h -o moc_world.cpp

moc_tools.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		tools.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tools.h -o moc_tools.cpp

moc_graphtype.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		view/graphtype.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/graphtype.h -o moc_graphtype.cpp

moc_legends.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		view/legends.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/legends.h -o moc_legends.cpp

moc_transform.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		transform.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform.h -o moc_transform.cpp

moc_integration.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		transform/integration.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform/integration.h -o moc_integration.cpp

moc_dialog.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_viewport.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		view/viewport.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view/viewport.h -o moc_viewport.cpp

compiler_rcc_make_all: qrc_qtgr.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qtgr.cpp
qrc_qtgr.cpp: qtgr.qrc \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/usr/bin/rcc -name qtgr qtgr.qrc -o qrc_qtgr.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

edit.o: edit.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		edit.h \
		core/globals.h \
		core/defines.h \
		core/pars.h \
		transform.h \
		dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edit.o edit.cpp

file.o: file.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		file.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

graphwidget.o: graphwidget.cpp graphwidget.h \
		mousecall.h \
		mainwindow.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o graphwidget.cpp

main.o: main.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		file.h \
		edit.h \
		view.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		view/viewport.h \
		tools.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tools.o: tools.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		tools.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o tools.cpp

view.o: view.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		view/viewport.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o view.cpp

ticks.o: view/ticks.cpp view.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		view/viewport.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ticks.o view/ticks.cpp

symbols.o: view/symbols.cpp view/symbols.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		view.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		view/viewport.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbols.o view/symbols.cpp

world.o: view/world.cpp view.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view/symbols.h \
		dialog.h \
		view/ticks.h \
		view/world.h \
		view/graphtype.h \
		view/legends.h \
		view/viewport.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o world.o view/world.cpp

alerts.o: core/alerts.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o alerts.o core/alerts.c

checkon.o: core/checkon.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o checkon.o core/checkon.c

chersh.o: core/chersh.c core/hersh.h \
		core/special.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o chersh.o core/chersh.c

defaults.o: core/defaults.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o defaults.o core/defaults.c

draw.o: core/draw.c core/symdefs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o draw.o core/draw.c

drawticks.o: core/drawticks.c core/globals.h \
		core/defines.h \
		core/pars.h \
		core/externs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o drawticks.o core/drawticks.c

events.o: core/events.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o events.o core/events.c

files.o: core/files.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o files.o core/files.c

fit.o: core/fit.c core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fit.o core/fit.c

graphutils.o: core/graphutils.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o graphutils.o core/graphutils.c

objutils.o: core/objutils.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objutils.o core/objutils.c

pars.o: core/pars.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pars.o core/pars.c

plotone.o: core/plotone.c core/globals.h \
		core/defines.h \
		core/pars.h \
		core/symdefs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o plotone.o core/plotone.c

qtlib.o: core/qtlib.c core/externs.h \
		core/patterns.h \
		graphwidget.h \
		mousecall.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o qtlib.o core/qtlib.c

utils.o: core/utils.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o utils.o core/utils.c

setutils.o: core/setutils.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setutils.o core/setutils.c

getparms.o: core/getparms.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o getparms.o core/getparms.c

setprops.o: core/setprops.c core/globals.h \
		core/defines.h \
		core/pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setprops.o core/setprops.c

graphtype.o: view/graphtype.cpp view/graphtype.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphtype.o view/graphtype.cpp

legends.o: view/legends.cpp view/legends.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		core/globals.h \
		core/defines.h \
		core/pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o legends.o view/legends.cpp

transform.o: transform.cpp transform.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h \
		transform/integration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transform.o transform.cpp

integration.o: transform/integration.cpp transform/integration.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integration.o transform/integration.cpp

dialog.o: dialog.cpp dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

viewport.o: view/viewport.cpp view/viewport.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewport.o view/viewport.cpp

moc_edit.o: moc_edit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edit.o moc_edit.cpp

moc_file.o: moc_file.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_file.o moc_file.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_ticks.o: moc_ticks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ticks.o moc_ticks.cpp

moc_symbols.o: moc_symbols.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_symbols.o moc_symbols.cpp

moc_world.o: moc_world.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_world.o moc_world.cpp

moc_tools.o: moc_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tools.o moc_tools.cpp

moc_graphtype.o: moc_graphtype.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphtype.o moc_graphtype.cpp

moc_legends.o: moc_legends.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_legends.o moc_legends.cpp

moc_transform.o: moc_transform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transform.o moc_transform.cpp

moc_integration.o: moc_integration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_integration.o moc_integration.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_viewport.o: moc_viewport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewport.o moc_viewport.cpp

qrc_qtgr.o: qrc_qtgr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtgr.o qrc_qtgr.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/edit.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/file.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/graphwidget.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/main.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mainwindow.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/tools.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/ticks.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/symbols.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/world.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/alerts.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/checkon.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/chersh.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/defaults.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/draw.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/drawticks.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/events.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/files.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/fit.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/graphutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/objutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/pars.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/plotone.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/qtlib.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/utils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/setutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/getparms.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/setprops.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/graphtype.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/legends.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/integration.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/dialog.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/viewport.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/edit.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/file.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/graphwidget.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/globals.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/defines.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/pars.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/externs.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/hersh.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/patterns.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/special.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/core/symdefs.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mainwindow.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mousecall.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/ticks.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/symbols.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/world.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/tools.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/graphtype.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/legends.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/integration.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/dialog.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view/viewport.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/qtgr.qrc $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/qtgr.pro $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_DIR) /home/msto/code/pappus/qtgr/images $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/edit.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/file.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphwidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mainwindow.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/tools.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ticks.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/symbols.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/world.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/alerts.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/checkon.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/chersh.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/defaults.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/draw.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/drawticks.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/events.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/files.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/fit.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/objutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/pars.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/plotone.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtlib.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/utils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/getparms.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setprops.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphtype.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/legends.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/transform.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/integration.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/dialog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/viewport.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/edit.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/file.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/globals.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/defines.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/pars.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/externs.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/hersh.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/patterns.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/special.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/symdefs.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mainwindow.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mousecall.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ticks.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/symbols.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/world.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/tools.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphtype.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/legends.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/transform.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/integration.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/dialog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/viewport.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtgr.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtgr.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/images
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

