#############################################################################
# Makefile for building: qtgr
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sat Jul 27 14:13:19 2013
# Project:  qtgr.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile qtgr.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = edit.cpp \
		file.cpp \
		graphwidget.cpp \
		main.cpp \
		mainwindow.cpp \
		tools.cpp \
		view.cpp \
		view_ticks.cpp \
		view_symbols.cpp \
		view_world.cpp \
		alerts.c \
		checkon.c \
		chersh.c \
		defaults.c \
		draw.c \
		drawticks.c \
		events.c \
		files.c \
		fit.c \
		graphutils.c \
		objutils.c \
		pars.c \
		plotone.c \
		qtlib.c \
		utils.c \
		setprops.c \
		setutils.c \
		getparms.c \
		view_graphtype.cpp \
		view_legends.cpp \
		transform.cpp \
		transform/integration.cpp \
		dialog.cpp moc_edit.cpp \
		moc_file.cpp \
		moc_graphwidget.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp \
		moc_view_ticks.cpp \
		moc_view_symbols.cpp \
		moc_view_world.cpp \
		moc_tools.cpp \
		moc_view_graphtype.cpp \
		moc_view_legends.cpp \
		moc_transform.cpp \
		moc_integration.cpp \
		moc_dialog.cpp \
		qrc_qtgr.cpp
OBJECTS       = edit.o \
		file.o \
		graphwidget.o \
		main.o \
		mainwindow.o \
		tools.o \
		view.o \
		view_ticks.o \
		view_symbols.o \
		view_world.o \
		alerts.o \
		checkon.o \
		chersh.o \
		defaults.o \
		draw.o \
		drawticks.o \
		events.o \
		files.o \
		fit.o \
		graphutils.o \
		objutils.o \
		pars.o \
		plotone.o \
		qtlib.o \
		utils.o \
		setprops.o \
		setutils.o \
		getparms.o \
		view_graphtype.o \
		view_legends.o \
		transform.o \
		integration.o \
		dialog.o \
		moc_edit.o \
		moc_file.o \
		moc_graphwidget.o \
		moc_mainwindow.o \
		moc_view.o \
		moc_view_ticks.o \
		moc_view_symbols.o \
		moc_view_world.o \
		moc_tools.o \
		moc_view_graphtype.o \
		moc_view_legends.o \
		moc_transform.o \
		moc_integration.o \
		moc_dialog.o \
		qrc_qtgr.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtgr.pro
QMAKE_TARGET  = qtgr
DESTDIR       = 
TARGET        = qtgr

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtgr.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile qtgr.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile qtgr.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtgr1.0.0 || $(MKDIR) .tmp/qtgr1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents edit.h file.h graphwidget.h globals.h mainwindow.h mousecall.h view.h view_ticks.h view_symbols.h view_world.h tools.h view_graphtype.h view_legends.h transform.h transform/integration.h dialog.h .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents qtgr.qrc .tmp/qtgr1.0.0/ && $(COPY_FILE) --parents edit.cpp file.cpp graphwidget.cpp main.cpp mainwindow.cpp tools.cpp view.cpp view_ticks.cpp view_symbols.cpp view_world.cpp alerts.c checkon.c chersh.c defaults.c draw.c drawticks.c events.c files.c fit.c graphutils.c objutils.c pars.c plotone.c qtlib.c utils.c setprops.c setutils.c getparms.c view_graphtype.cpp view_legends.cpp transform.cpp transform/integration.cpp dialog.cpp .tmp/qtgr1.0.0/ && (cd `dirname .tmp/qtgr1.0.0` && $(TAR) qtgr1.0.0.tar qtgr1.0.0 && $(COMPRESS) qtgr1.0.0.tar) && $(MOVE) `dirname .tmp/qtgr1.0.0`/qtgr1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtgr1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_edit.cpp moc_file.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_view.cpp moc_view_ticks.cpp moc_view_symbols.cpp moc_view_world.cpp moc_tools.cpp moc_view_graphtype.cpp moc_view_legends.cpp moc_transform.cpp moc_integration.cpp moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_edit.cpp moc_file.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_view.cpp moc_view_ticks.cpp moc_view_symbols.cpp moc_view_world.cpp moc_tools.cpp moc_view_graphtype.cpp moc_view_legends.cpp moc_transform.cpp moc_integration.cpp moc_dialog.cpp
moc_edit.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		edit.h
	/usr/bin/moc $(DEFINES) $(INCPATH) edit.h -o moc_edit.cpp

moc_file.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		file.h
	/usr/bin/moc $(DEFINES) $(INCPATH) file.h -o moc_file.cpp

moc_graphwidget.cpp: mousecall.h \
		graphwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) graphwidget.h -o moc_graphwidget.cpp

moc_mainwindow.cpp: graphwidget.h \
		mousecall.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_symbols.h \
		view_ticks.h \
		view_world.h \
		view_graphtype.h \
		view_legends.h \
		view.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view.h -o moc_view.cpp

moc_view_ticks.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_ticks.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view_ticks.h -o moc_view_ticks.cpp

moc_view_symbols.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_symbols.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view_symbols.h -o moc_view_symbols.cpp

moc_view_world.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_world.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view_world.h -o moc_view_world.cpp

moc_tools.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		tools.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tools.h -o moc_tools.cpp

moc_view_graphtype.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_graphtype.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view_graphtype.h -o moc_view_graphtype.cpp

moc_view_legends.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_legends.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view_legends.h -o moc_view_legends.cpp

moc_transform.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		transform.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform.h -o moc_transform.cpp

moc_integration.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		transform/integration.h
	/usr/bin/moc $(DEFINES) $(INCPATH) transform/integration.h -o moc_integration.cpp

moc_dialog.cpp: mainwindow.h \
		graphwidget.h \
		mousecall.h \
		dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

compiler_rcc_make_all: qrc_qtgr.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qtgr.cpp
qrc_qtgr.cpp: qtgr.qrc \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/usr/bin/rcc -name qtgr qtgr.qrc -o qrc_qtgr.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

edit.o: edit.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		edit.h \
		globals.h \
		defines.h \
		pars.h \
		transform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edit.o edit.cpp

file.o: file.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		file.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

graphwidget.o: graphwidget.cpp graphwidget.h \
		mousecall.h \
		mainwindow.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o graphwidget.cpp

main.o: main.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		file.h \
		edit.h \
		view.h \
		view_symbols.h \
		view_ticks.h \
		view_world.h \
		view_graphtype.h \
		view_legends.h \
		tools.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tools.o: tools.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		tools.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o tools.cpp

view.o: view.cpp mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view.h \
		view_symbols.h \
		view_ticks.h \
		view_world.h \
		view_graphtype.h \
		view_legends.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o view.cpp

view_ticks.o: view_ticks.cpp view.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_symbols.h \
		view_ticks.h \
		view_world.h \
		view_graphtype.h \
		view_legends.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view_ticks.o view_ticks.cpp

view_symbols.o: view_symbols.cpp view.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_symbols.h \
		view_ticks.h \
		view_world.h \
		view_graphtype.h \
		view_legends.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view_symbols.o view_symbols.cpp

view_world.o: view_world.cpp view.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		view_symbols.h \
		view_ticks.h \
		view_world.h \
		view_graphtype.h \
		view_legends.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view_world.o view_world.cpp

alerts.o: alerts.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o alerts.o alerts.c

checkon.o: checkon.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o checkon.o checkon.c

chersh.o: chersh.c hersh.h \
		special.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o chersh.o chersh.c

defaults.o: defaults.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o defaults.o defaults.c

draw.o: draw.c symdefs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o draw.o draw.c

drawticks.o: drawticks.c globals.h \
		defines.h \
		pars.h \
		externs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o drawticks.o drawticks.c

events.o: events.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o events.o events.c

files.o: files.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o files.o files.c

fit.o: fit.c defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fit.o fit.c

graphutils.o: graphutils.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o graphutils.o graphutils.c

objutils.o: objutils.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objutils.o objutils.c

pars.o: pars.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pars.o pars.c

plotone.o: plotone.c globals.h \
		defines.h \
		pars.h \
		symdefs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o plotone.o plotone.c

qtlib.o: qtlib.c externs.h \
		patterns.h \
		graphwidget.h \
		mousecall.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o qtlib.o qtlib.c

utils.o: utils.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o utils.o utils.c

setprops.o: setprops.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setprops.o setprops.c

setutils.o: setutils.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setutils.o setutils.c

getparms.o: getparms.c globals.h \
		defines.h \
		pars.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o getparms.o getparms.c

view_graphtype.o: view_graphtype.cpp view_graphtype.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view_graphtype.o view_graphtype.cpp

view_legends.o: view_legends.cpp view_legends.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h \
		globals.h \
		defines.h \
		pars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view_legends.o view_legends.cpp

transform.o: transform.cpp transform.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transform.o transform.cpp

integration.o: transform/integration.cpp transform/integration.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integration.o transform/integration.cpp

dialog.o: dialog.cpp dialog.h \
		mainwindow.h \
		graphwidget.h \
		mousecall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

moc_edit.o: moc_edit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edit.o moc_edit.cpp

moc_file.o: moc_file.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_file.o moc_file.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_view_ticks.o: moc_view_ticks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view_ticks.o moc_view_ticks.cpp

moc_view_symbols.o: moc_view_symbols.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view_symbols.o moc_view_symbols.cpp

moc_view_world.o: moc_view_world.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view_world.o moc_view_world.cpp

moc_tools.o: moc_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tools.o moc_tools.cpp

moc_view_graphtype.o: moc_view_graphtype.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view_graphtype.o moc_view_graphtype.cpp

moc_view_legends.o: moc_view_legends.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view_legends.o moc_view_legends.cpp

moc_transform.o: moc_transform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transform.o moc_transform.cpp

moc_integration.o: moc_integration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_integration.o moc_integration.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

qrc_qtgr.o: qrc_qtgr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtgr.o qrc_qtgr.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/edit.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/file.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/graphwidget.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/main.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mainwindow.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/tools.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_ticks.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_symbols.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_world.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/alerts.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/checkon.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/chersh.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/defaults.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/draw.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/drawticks.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/events.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/files.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/fit.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/graphutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/objutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/pars.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/plotone.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/qtlib.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/utils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/setprops.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/setutils.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/getparms.c $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_graphtype.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_legends.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/integration.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/dialog.cpp $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/edit.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/file.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/graphwidget.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/globals.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mainwindow.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/mousecall.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_ticks.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_symbols.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_world.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/tools.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_graphtype.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/view_legends.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/transform/integration.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/dialog.h $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/qtgr.qrc $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_FILE) /home/msto/code/pappus/qtgr/qtgr.pro $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/
	-$(INSTALL_DIR) /home/msto/code/pappus/qtgr/images $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/edit.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/file.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphwidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mainwindow.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/tools.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_ticks.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_symbols.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_world.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/alerts.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/checkon.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/chersh.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/defaults.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/draw.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/drawticks.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/events.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/files.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/fit.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/objutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/pars.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/plotone.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtlib.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/utils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setprops.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/setutils.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/getparms.c 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_graphtype.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_legends.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/transform.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/integration.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/dialog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/edit.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/file.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/graphwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/globals.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mainwindow.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/mousecall.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_ticks.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_symbols.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_world.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/tools.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_graphtype.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/view_legends.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/transform.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/integration.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/dialog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtgr.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/qtgr.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/images
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/mainwindows/qtgr/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

